name: MirrorSC-Actions
on:
  push:
    branches: [sc]

env:
  TZ: America/Recife
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
      - name: Configurando Instancia
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}" 
          git config --global pull.rebase false
          git config --global credential.helper store
          echo "https://${{ secrets.GH_NAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clonando Repositorio
        continue-on-error: true
        run: |
         git clone https://github.com/Surya-Trees-SC/mirror-leech-telegram-bot.git MirrorSC
          
      - name: Instalando Dcker
        continue-on-error: true
        run: |
          sudo curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

      - name: Corriendo el Bot
        timeout-minutes: hori
        continue-on-error: true
        run: |
          cd MirrorSC
          sudo docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          sudo docker run --privileged --rm -i mirror-bot
           
      - name: Proceso de Automizacion
        timeout-minutes: 5
        continue-on-error: true
        run: |
          echo "[LOOP] Mirror USA Corriendo por horo horas"
         
